version: "3.7"
services:
  hato_server:
    image: hato/hato_server
    build: server/
    environment:
      - hato_pgsql=Host=localhost;Database=server_pgsql;Port=5432;Username=postgres;Password=postgres
    env_file: .env
    # volumes:
    #   - ./cert:s
    links:
      - server_pgsql
    depends_on:
      - server_pgsql
    ports:
      - 80:80
  server_pgsql:
    image: hato/pgsql_jieba
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file: .env
    build:
      context: .
      dockerfile: pgsql-jieba.Dockerfile
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
